### ISSUE TITLE
When removing  family member from the household after putting the reason for removing the client and the date of removal and saving the swahili message that appears "Una uhakika unataka kuondoa taarifa za X null null...? The null null should be removed.

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#159]

**Comment by devcolonel** [comment]
@issyzac I did several test on different house hold I Found that the issue of appending null on family member name is due to middle name being null so I tried to provide the middle name the null on the dialog disappear.
so this issue is due to dummy data.
