### ISSUE TITLE
The word "Sync" is still in english even on the kiswahili version of the app. It needs to be translated>>"oanisha"

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#179]

**Comment by devcolonel** [comment]
@issyzac I found that the sync label  is within the ### opensrp-client-chw-core-2.1.3-SNAPSHOT-KK-9 so even if we change now it will fix the issue but once we update the library we will have the same issue.
Permanent solution is to update it once we are releasing the library new version
