### ISSUE TITLE
The system allows th user to continue even without taking a picture of the signed consent form or recording the location

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#206]

**Comment by gosso22** [comment]
Made changes to the native forms library - the branch can be found here
https://github.com/opensrp/opensrp-client-native-form/tree/kk-39-hf-referral original branch at opensrp account and
https://github.com/d-tree-org/opensrp-client-native-form/tree/kk-master branch in our account

The new version of chw-core library is 2.1.3-SNAPSHOT-KK-13 and associated PR https://github.com/d-tree-org/opensrp-client-chw-core/pull/38 to upgrade native forms

![Image](https://user-images.githubusercontent.com/2742891/214868082-96dcfd68-c584-4fb4-8b1b-d346cdd7da0e.jpg)

@devcolonel you can go ahead and make necessary changes to the individual forms and test it out.

@issyzac - I have tested the gps required and for me at least it was preventing me moving forward even after I had recorded longitude and latitude. I suggest that we test this out extensively before we ship it out.

**Comment by issyzac** [comment]
@gosso22 as we discussed earlier I suggest we do not make that a mandatory field for now due to the fact that other challenges to the GPS unrelated to the app features may still prevent the user from continuing with the rest of the process
