### ISSUE TITLE
Child Profile : On child profile-age of child (3d) still in english even on the swahili app

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#222]

**Comment by maulidkategile** [comment]
@Zubakes What is the status on this item?

**Comment by Zubakes** [comment]
@maulidkategile this still needs to be worked on. Or maybe what do you mean?

**Comment by maulidkategile** [comment]
@Zubakes I am just making a followup for more clarification if there was a discussion around this item because it is in ON HOLD status. If it has to be worked on my end I may need to understand it more.

**Comment by Zubakes** [comment]
@maulidkategile for this issue, the ages of the children appear in English on their profile. This can be confusing for the CHWs to know the age of the child. I am available if you may want to discuss through call.

**Comment by maulidkategile** [comment]
@Zubakes You can schedule for that or join us on tomorrow daily standup

**Comment by Zubakes** [comment]
@maulidkategile Is it urgent for you? If not, I can join tomorrows call.

**Comment by maulidkategile** [comment]
@Zubakes No problem you can join a call tomorrow

**Comment by Zubakes** [comment]
@maulidkategile as it is on the app we have for example child  X, 1d can this be child X, Siku1?; Child X, 8w could be Child X, wiki 8 ,Child X, 4w 3d could be Child X, 4wk sk3, Child X 3m 1 w could be Child X mz 3 wk 1.

**Comment by maulidkategile** [comment]
@Zubakes That is well noted but as it seems the standard way of implementation in OpenSRP is for example

- child X, 1d will be child X, 1sk 

- child X, 7w 3d will be child X, 7wk 3sk, 

- child X, 3m 1w will be child X, 3mz 1wk 

As to easily accommodates different languages. So if that is okay then we can implement it on the OpenSRP standard format but if you think there is a necessity to change the format to the one you recommended then may be we can hear from @issyzac and @gosso22 for their inputs/suggestions.

**Comment by Zubakes** [comment]
Hi Maulid,
This is fine for now.

**Comment by issyzac** [comment]
@Zubakes has this been tested already? Can you confirm that its working as expected?

**Comment by Zubakes** [comment]
@maulidkategile @issyzac Swahili test: Passed
