### ISSUE TITLE
In Communication Assessment, there is a box that is in Swahili. Also should the icon be yellow when “Yes” and “Tries to force the smile/…”

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#273]

**Comment by Zubakes** [comment]
@issyzac the icon turned yellow, although the message is still in swahili.

**Comment by Zubakes** [comment]
The english translation is "Can you show me how you communicate with your baby? What do you think your child is learning while you communicate?"

**Comment by Zubakes** [comment]
RT comments: "If I declare that the mother doesn’t communicate with the child the icon is still white and it should be green. Moreover, the app thinks that I didn’t answer the module so doesn’t allow me to save my progress."
