### ISSUE TITLE
Malnutrition/Anemia, in the sentences that show up in the summary, it should say Measure MUAC: red or Anemia:Yes AND the icon to be yellow if it’s the case.

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#277]

**Comment by issyzac** [comment]
@Zubakes can you let us know if this item has been tested?

**Comment by Zubakes** [comment]
@issyzac I was having a hard time getting a child with this module. I even tried to do move the date of birth to reflect the dates for this visit but still doesn't show up. So was not able to test. Could you try from your end?

**Comment by Zubakes** [comment]
@issyzac I was able to test! It is fine now :)

**Comment by issyzac** [comment]
Okay, will close this then

**Comment by Zubakes** [comment]
@issyzac moved it to Done.
