### ISSUE TITLE
In Neonatal danger signs: it should be yellow when a danger sign is recorded.

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#278]

**Comment by issyzac** [comment]
@devcolonel can you check this item, the team tested and they reported that it has not passed

**Comment by devcolonel** [comment]
@issyzac I tested and confirm the evaluation is done correctly


![Image](https://user-images.githubusercontent.com/100844435/214296941-fa101400-1a37-422e-b79a-b9ac23d7fff8.jpg)

**Comment by issyzac** [comment]
👍, @Zubakes this is also done but was commented by the research team that it was not done

**Comment by issyzac** [comment]
@Zubakes moving this to testing as well once you confirm we can close this one too

**Comment by Zubakes** [comment]
@issyzac Yes I had tested it and it passed.

**Comment by Zubakes** [comment]
@issyzac @devcolonel This has passed
