### ISSUE TITLE
In breastfeeding, the item should have a yellow icon status if the woman says she didn’t breastfed the siblings

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#281]

**Comment by issyzac** [comment]
@devcolonel can you also check this item and confirm that it was implemented as requested?

**Comment by devcolonel** [comment]
![Image](https://user-images.githubusercontent.com/100844435/214296407-5a29ba1e-1f0d-427a-818c-2c69d1a5bb6d.jpg)
![Image](https://user-images.githubusercontent.com/100844435/214296409-0eab415e-dc5f-4489-a9dd-8e7f6beeaf33.jpg)

**Comment by issyzac** [comment]
@Zubakes Moving it to testing for testing for your confirmation then we can close this one up

**Comment by Zubakes** [comment]
@devcolonel @issyzac Yellow icon status: Passed
