### ISSUE TITLE
[DATA] Registration duration

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#287]
Using start and end time to calculate duration is working fine only during home visit for combined events required fixing

**Comment by nkafwimi** [comment]
The start and end times fields are capturing the correct information, however the field duration within the event always records 0

**Comment by issyzac** [comment]
Hi @nkafwimi , after our earlier conversation is there anything else that is required from this item?

**Comment by nkafwimi** [comment]
@issyzac I've marked this item as "Done"
