### ISSUE TITLE
Add on the update family member form a field that captures the type of action to determine if the change is for a primary caregiver or head of the household

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#290]
The form associated might be the update household information

**Comment by nkafwimi** [comment]
When updating the primary caregiver, there are two events that are created: 1) Update Family Member Relations, and 2) Update Family Relations

**Comment by Zubakes** [comment]
@issyzac and @nkafwimi was this to be implemented on the dashboard or on the app?

**Comment by issyzac** [comment]
@Zubakes confirming this with @nkafwimi and will let you know the status of this?

**Comment by issyzac** [comment]
But we had changed the approach to this that did not require us to implement what this issue was suggesting

**Comment by Zubakes** [comment]
@issyzac I though that was for the add the consent form which is a different item? I get that it may be related to this, but just wanted clarity incase it is different.

**Comment by issyzac** [comment]
no it does not relate to this, this is a different item that was requested by @nkafwimi

**Comment by Zubakes** [comment]
Okay @issyzac

**Comment by nkafwimi** [comment]
@issyzac we just need to get the date for when this functionality was implemented, which will help us filter out the data during analysis
