### ISSUE TITLE
On pregnancy outcome the value captured on select option is Question instead of selected value

### ISSUE THREAD

**Issue by devcolonel** [d-tree-org/opensrp-client-chw-kk#294]
- preg_outcome -> incorrect data is captured e.g. captures “Matokeo ya ujauzito *” instead of the select options value

- delivery_place -> incorrect data is captured e.g. captures “Mahali alipojifungulia mama *” instead of the actual select option value

**Comment by issyzac** [comment]
@Zubakes see @devcolonel comments FYR

**Comment by Zubakes** [comment]
@devcolonel Is this to be tested on the app?

**Comment by issyzac** [comment]
This is to be tested by @nkafwimi
