### ISSUE TITLE
On pregnancy outcome the father information form is generated twice if the children are more than one

### ISSUE THREAD

**Issue by maulidkategile** [d-tree-org/opensrp-client-chw-kk#297]

**Comment by devcolonel** [comment]
https://github.com/OpenSRP/opensrp-client-native-form/issues/172#issuecomment-478874921

**Comment by issyzac** [comment]
@maulidkategile @devcolonel can we confirm if this item was incorporated?

**Comment by maulidkategile** [comment]
I can confirm that the item was incorporated

**Comment by issyzac** [comment]
Okay thanks, I will go ahead and close this
