### ISSUE TITLE
[Duplicate] Add a consent field in a form for changing a primary care giver

### ISSUE THREAD

**Issue by maulidkategile** [d-tree-org/opensrp-client-chw-kk#298]

**Comment by issyzac** [comment]
Isaya to discuss this with Grace

**Comment by issyzac** [comment]
@Zubakes I think this has already been done, can you confirm?

**Comment by Zubakes** [comment]
@issyzac this has not been done. I believe this was the item we had discussed and said it would not be implemented we do not expect a situation where there would be two primary caregivers at once except only during pregnancy outcome.

**Comment by issyzac** [comment]
Got it! so there are two parts to this item, 1 is during pregnancy outcome and another one is during adding a new caregiver to the family so I will go ahead and close this item as far as tracking pregnancy outcome and open one in the current sprint tracking consent for adding a caregiver to the household
