### ISSUE TITLE
[DATA] missing data and incorrect data capturing: event_anc_registration

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#320]
Link: https://app.periscopedata.com/app/d-tree/1053391/Kizazi-Kijacho---Test-dashboard?widget=15036519&udv=0

1. no_miscarriage -> empty  
2. delivery_method -> incorrect data is captured e.g. captures “ture” instead of the name/delivery type method 
3. person_assit -> empty 
4. name_person_assit -> empty  
5. marital_status -> incorrect data is capture on some records e.g. captures “Whats the pregnant woman current marital status?” or “Hali ya ndoa” instead of the actual marital status  
6. accessibility_issues -> incorrect data is capture on some records e.g. captures “true” or “Does the woman experience difficulty in doing any of the following?” instead of the select options value
7. accessibility_issue_other -> empty  
8. economic_activities -> incorrect data is capture on some records e.g. captures “true” instead of the select options value AND both Swahili and English language shows  
9. health_insurance -> incorrect data is capture on some records e.g. captures “Does the pregnant mother have health insurance”,  or “Je, mama mjamzito ana bima ya afya?” instead of “true” or “false”
10. symptoms_prev_preg  -> incorrect data is capture on some records e.g. captures “true” instead of the select options value
11. preferred_name - > empty
12. dob_unknown -> incorrect data is captured e.g. captures “ DOB unknown?” or “Tarehe ya kuzaliwa haijulikani?” instead of “true” or “false”
13. other_number -> empty
14. substance_use -> incorrect data is captured on some records e.g. captures “Does the pregnant mother usually smoke cigarettes, drink alcohol, use drugs?” or “Je unavutaga sigara, kunywa pombe, au kutumia madawa ya kulevya?”

**Comment by nkafwimi** [comment]
When a user indicates that the client's dob is unknown, i.e., dob_unknown we are not seeing the associated field for capturing the client's age
