### ISSUE TITLE
Add consent information capturing when adding a new caregiver to a household

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#322]

**Comment by Zubakes** [comment]
@maulidkategile @issyzac I believe this item was put on pause?

**Comment by issyzac** [comment]
@Zubakes this was implemented when adding a new member in the household and the member is not another ANC mother but another caregiver

**Comment by Zubakes** [comment]
@issyzac Add consent information for adding a new caregiver to a household test: Passed
