### ISSUE TITLE
Phone number of the person who will assist her is personal information of a third person that didn’t consent. The phone number field should be removed

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#323]

**Comment by issyzac** [comment]
Also check the phone validation in all the other places that requires phone number (Father details)

**Comment by Zubakes** [comment]
@issyzac @maulidkategile ANC Reg form-Phone number remove test: Passed
Phone number of father still asked on Baby registration. To remove.

**Comment by Zubakes** [comment]
@maulidkategile @issyzac remove phone number of father: Passed
