### ISSUE TITLE
On the ANC Registration form, there's inconsistency in the naming of the "fieldCode" and "formSubmissionField" for fam_name -- see attached screenshot

### ISSUE THREAD

**Issue by nkafwimi** [d-tree-org/opensrp-client-chw-kk#324]

**Comment by nkafwimi** [comment]
![Image](https://user-images.githubusercontent.com/105015277/214081750-bfbc17d7-a359-4f1f-a9de-af38eae5dbc2.png)

**Comment by devcolonel** [comment]
@nkafwimi on Data which key are you using to read the value?

**Comment by nkafwimi** [comment]
@devcolonel the field that's referenced is the "humaReadableValues", but also sometimes in troubleshooting we reference "formSubmissionField"

**Comment by issyzac** [comment]
This has been resolved with Neema.
