### ISSUE TITLE
Pregnancy Outcome : When a user indicates that the client's dob is unknown, i.e., dob_unknown we are not seeing the associated field for capturing the client's age

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#329]

**Comment by devcolonel** [comment]
@nkafwimi  the field for capturing the client age is the one which shown after the unknown checkbox is checked with the label _**How old is the baby (in days)**_



![Image](https://user-images.githubusercontent.com/100844435/216303560-c86cfbd2-a929-4cf3-9998-da70fd640a6e.jpeg)



![Image](https://user-images.githubusercontent.com/100844435/216303697-deabdf27-6833-4d7e-894a-923e1e4f53a8.jpeg)

**Comment by nkafwimi** [comment]
@devcolonel and @issyzac this issue is observed on the ANC registration form and relates to a scenario when a pregnant woman is registered not a baby.

@devcolonel thanks for sharing about the pregnancy outcome scenario, I remember us having this discussion to clarify and everything was clear

**Comment by devcolonel** [comment]
@issyzac @nkafwimi 
 I have a question on the issue of the ANC: once the dob_unknown checkbox is checked, we don't have the field to capture the client's age.
Is the field not shown on the app once dob_unknown is checked, or are we not capturing the value for that field?

**Comment by issyzac** [comment]
@devcolonel in any of the user registrations there should be a field that captures the date of birth, and whenever the dob is unknown there should be a field that captures the age and for this case @nkafwimi cannot see the age of the ANC mother whenever the dob field is unknown in the dashboard so basically what we need to do is check if the field is being captured on the app, i.e. whenever the user says they don't know the date of birth there should be an age field that shows up (mandatory) and after its filled then it should also be in the events table. If currently that's how it is then we need to know so that we can move the troubleshooting to the server and the ETL

**Comment by nkafwimi** [comment]
I was able to confirm that we can pull the data from the raw clients events table for the instances where the dob is unknown



![Image](https://user-images.githubusercontent.com/105015277/220270107-afc41388-a032-4734-b452-443e407c4081.png)
