### ISSUE TITLE
Postpartum Danger signs still show the green icon when risk signs are declared. Same with Toddler danger signs. It should be yellow.

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#332]

**Comment by Zubakes** [comment]
@issyzac, for PNC danger signs test is: Passed. 
Although I saw that the "Save and Refer to a health facility" icon still shows even when the response is No to "Based on the discussions, do you think......" 
For toddler danger sign test is: Passed

**Comment by issyzac** [comment]
When they say no save and refer should not appear let me take a look at that

**Comment by Zubakes** [comment]
@issyzac "Based on the discussions, do you think......" test: Passed
