### ISSUE TITLE
Restrict number of surviving children entered to less than 50 and Miscarriages 45

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#336]

**Comment by Zubakes** [comment]
@issyzac Restrict number of surviving children entered less than 50: Passed
Misscariages: Not Passed (allows you to save numbers greater than 45)

**Comment by issyzac** [comment]
![Image](https://user-images.githubusercontent.com/5725601/218998034-d5e968dc-2e95-4c65-b767-1ef150a67183.jpg)
![Image](https://user-images.githubusercontent.com/5725601/218998036-3a17c123-2217-41a0-9f82-308310cdda2d.jpg)

**Comment by Zubakes** [comment]
@issyzac Restrict number test: Passed
