### ISSUE TITLE
Remove the edit functionality for the ANC Visit.

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#337]
Once the CHW has conducted an ANC Visit, they shouldnt be able to go back and edit the visit.

**Comment by maulidkategile** [comment]
@Zubakes What is the status on this item?

**Comment by Zubakes** [comment]
@maulidkategile this needs to be worked on.

**Comment by Zubakes** [comment]
@maulidkategile as we discussed this morning. This has been put on hold. No need to work on for now.
