### ISSUE TITLE
Essential New Born Care: Breastfeeding should show a yellow icon if the child is being feeded with soft food very early

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#338]

**Comment by Zubakes** [comment]
@gosso22 this should be conditioned for the visits within the first six months. After that it should be green when fed soft foods (yellow when they are not)

**Comment by devcolonel** [comment]
@gosso22 after six month still shows yellow Icon when child is being feed with soft food so we need to update the code to handle that too

**Comment by issyzac** [comment]
![Image](https://user-images.githubusercontent.com/5725601/219004572-55c2fc1d-6994-4f5a-9c03-00317336bad3.jpg)
![Image](https://user-images.githubusercontent.com/5725601/219004571-d3a65168-adc2-4606-90de-d5b02ca94c92.jpg)

**Comment by Zubakes** [comment]
@issyzac is this reflected on the updated release? In the version I have, the changes are not there.

**Comment by Zubakes** [comment]
@issyzac Breastfeeding icon green: Passed
