### ISSUE TITLE
In Immunizations, in the question “why did the child not receive a vaccine?” add options “I didn’t know”   “I couldn’t go to the HF” and allow multiple answers because for older ages we are asking about a long list of vaccines.

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#339]

**Comment by issyzac** [comment]
look at Data dictionary rows 189-195 on the “Visit Child Updated”

**Comment by Zubakes** [comment]
@issyzac to edit the following:
Eng:
Could not go to the health facility: I could not take the child to receive the vaccine
Does not know: I did not know about the vaccine
Swahili
I did not now about the vaccine: Sikujua kuhusu hio chanjo
 I could not take the child to receive the vaccine: Sikuweza kumpeleka mtoto kupata chanjo

**Comment by issyzac** [comment]
@Zubakes picked up and updated!

**Comment by Zubakes** [comment]
@issyzac has the new release been made which will reflect this? Currently do not see it.

**Comment by Zubakes** [comment]
@issyzac
 Eng:
"Could not go to the health facility: I could not take the child to receive the vaccine
Does not know: I did not know about the vaccine" test: Passed
Multiple answers test: Passed
Swahili
"I did not now about the vaccine: Sikujua kuhusu hio chanjo
I could not take the child to receive the vaccine: Sikuweza kumpeleka mtoto kupata chanjo" test: Passed
