### ISSUE TITLE
Malaria Prevention in the child visits, icon should be yellow if LLIN condition is poor. A message should show up for the CHW to know this is an observational answer (to be checked with their own eyes if possible)

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#340]

**Comment by issyzac** [comment]
Exact message to be added before the question about LLIN: 

“If there is a LLIN in the house, ask the mother if you can take a quick look at it. Now, answer the next question without reading it out loud. If not possible to have a look at LLIN, ask the mother about the conditions of the LLIN and read the options for her.

**Comment by gosso22** [comment]
@issyzac - do we have the translation for the above text? Also should this be a toaster note?

**Comment by devcolonel** [comment]
@Zubakes the swahili translation for  this text is missing 
**If there is a LLIN in the house, ask the mother if you can take a quick look at it. Now, answer the next question without reading it out loud. If not possible to have a look at LLIN, ask the mother about the conditions of the LLIN and read the options for her.**

**Comment by devcolonel** [comment]
**Ikiwa kuna chandarua ndani ya nyumba, muulize mlezi kama unaweza kuiona. Sasa, jibu swali linalofuata bila kumsomea mlezi kwa sauti. Kama haiwezekani kuiona chandarua, muulize mlezi hali ya chandarua.**

**Comment by issyzac** [comment]
@Zubakes This has been picked up and updated by Mario today

**Comment by Zubakes** [comment]
@issyzac I assume this will be reflected in the newer release?

**Comment by Zubakes** [comment]
@gosso22 @issyzac Observational message in swahili app: Passed
