### ISSUE TITLE
Expand on the "other" reasons on removing household/client record functionality to account for records removed because user entered incorrect information

### ISSUE THREAD

**Issue by nkafwimi** [d-tree-org/opensrp-client-chw-kk#344]

**Comment by nkafwimi** [comment]
@issyzac could you please review this and prioritise the item based on what else you have on your plate

**Comment by nkafwimi** [comment]
@issyzac thanks for reviewing this item. I'm including the reasons to be added below:

•	Created duplicate records (Nilishasajiri mteja/kaya hii) 
•	Made mistake recording information (Nimeingiza taarifa isiyo sahihi)

**Comment by nkafwimi** [comment]
@issyzac link to the information added on the data dictionary, tabs: Remove family member, Closure of household record

https://docs.google.com/spreadsheets/d/108AxdYXqTM6RRF6oMIufZ2lpxqyeJHoWGSt46-lBn_g/edit#gid=741049060

**Comment by issyzac** [comment]
![Image](https://user-images.githubusercontent.com/5725601/218666840-eed826eb-f2a7-4e8f-98f5-392b1d446f24.jpg)

**Comment by Zubakes** [comment]
@issyzac remove household: Passed
Remove client record: Not passed

**Comment by issyzac** [comment]
FIXED: Here is a screenshot of removing a child 

![Image](https://user-images.githubusercontent.com/5725601/218778466-8cc44c37-6115-4ad3-a2d5-41aa0a79cb13.png)

**Comment by issyzac** [comment]
And here is removing any other family member



![Image](https://user-images.githubusercontent.com/5725601/218778890-994059bd-b4e5-42f5-bd08-521ffc35e98f.png)

**Comment by Zubakes** [comment]
@issyzac I am reviewing in the app and it is not reflecting on the child yet.
Also reason "revoked consent" is missing when removing PNC client
Also on swahili version:
Revoked consent translation missing-->amebatilisha ridhaa

**Comment by Zubakes** [comment]
@issyzac remove child: Passed
remove household: Not passed (swahili translation mising amebatilisha ridhaa)*although to discuss if this reason should be included when removing household
remove PNC: Passed

**Comment by issyzac** [comment]
@Zubakes 

This is the data dictionary for household removal there is no Revoking consent

![Image](https://user-images.githubusercontent.com/5725601/219306251-fed16249-a33e-49d7-8aaa-07b7ff517311.png)

**Comment by Zubakes** [comment]
@issyzac ohh I see. That is fine then.
