### ISSUE TITLE
Enable editing EDI-ID

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#349]

**Comment by issyzac** [comment]
Done!

**Comment by issyzac** [comment]
![Image](https://user-images.githubusercontent.com/5725601/218668269-cf5991d8-1786-4914-9bcd-661901b903ac.jpg)

**Comment by Zubakes** [comment]
@issyzac I am not able to find this on the app.

**Comment by issyzac** [comment]
@Zubakes You need to edit registration information of ANC Women to be able to edit EDI ID since they are the only ones registered with one

**Comment by Zubakes** [comment]
@issyzac for edit family member it only stops on the first form that captures consent. It does not have a second page for edit ANC Reg form.

**Comment by Zubakes** [comment]
@issyzac I need more guidance on this.

**Comment by Zubakes** [comment]
@issyzac Enable editing EDI-ID: Passed
