### ISSUE TITLE
Cross check the criteria for removal of PNC Clients. Ideally they should be removed once all the visits have been completed and the age is above 42 days

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#384]

**Comment by issyzac** [comment]
@maulidkategile can you add your review for this item here?

**Comment by maulidkategile** [comment]
@Zubakes The main criteria for the PNC clients to disappear in the list of active PNC clients is age. After 60 days have passed and the child is 60 days old the PNC client will disappear despite other criteria like last visit overdue.
