### ISSUE TITLE
Update Care for child development (CCD): Communication Assessment and Counselling

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#405]

**Comment by issyzac** [comment]
https://docs.google.com/spreadsheets/d/1tx5wC2qprwsizYv7lDoQ2LAEyUvAoX_K/edit#gid=1461766659&range=B46

**Comment by gosso22** [comment]
I was not able to find the swahili content for CHW information: Say, "When i come back for the next visit, I would like to see the playing toy(s) that you have prepared and how you communicate and play with your child". @Zubakes
