### ISSUE TITLE
Update Care for child development (CCD): Child development screening assessment

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#409]

**Comment by issyzac** [comment]
https://docs.google.com/spreadsheets/d/1tx5wC2qprwsizYv7lDoQ2LAEyUvAoX_K/edit#gid=1461766659&range=B105

**Comment by devcolonel** [comment]
@Zubakes  @issyzac  on the sheet it says this inform is already in the app  https://docs.google.com/spreadsheets/d/1tx5wC2qprwsizYv7lDoQ2LAEyUvAoX_K/edit#gid=1461766659&range=B127
but I cant locate it , if possible can I have message before it was updated?

Also can I have the translation for this https://docs.google.com/spreadsheets/d/1tx5wC2qprwsizYv7lDoQ2LAEyUvAoX_K/edit#gid=1461766659&range=B128

**Comment by issyzac** [comment]
@devcolonel For the second question isnt the translation on the right of that column?
