### ISSUE TITLE
To add a question on the relationship of the person who came to the group session to the mother of the child

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#471]

**Comment by issyzac** [comment]
@Zubakes Can you provide a bit more details on this?

**Comment by Zubeda94** [comment]
@issyzac 
![Screenshot_20230921-142847_Kizazi Kijacho](https://github.com/d-tree-org/opensrp-client-chw-kk/assets/140724155/10a1f175-d7aa-4824-a6f5-3bab69fe1e0c)

**Comment by Zubeda94** [comment]
@issyzac on the screen shot above, when the CHW selects No, the next question which asks the relationship of the child to the person, the response should not allow the chw to select multiple as it can only be one person.

**Comment by Zubeda94** [comment]
Also, after that there should be a similar question to the one we have when the response is yes, so as to know the relationship of the other people (if any) that came with the PC giver

**Comment by Zubeda94** [comment]
@issyzac when do you think this item will be finalized for testing?
